###
GET http://localhost:9000/api/roles HTTP/1.1

###

POST http://localhost:9000/api/roles HTTP/1.1
Content-Type: application/json

{
    "ID_Rol": 4,
    "TipoRol": "Nuevo Rol"
}

###

DELETE http://localhost:9000/api/roles/2 HTTP/1.1

###

PUT http://localhost:9000/api/roles/1 HTTP/1.1
Content-Type: application/json

{
    "TipoRol": "Administrador Actualizado"
}

###

GET http://localhost:9000/api/usuarios/ HTTP/1.1

###

POST http://localhost:9000/api/usuarios/ HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Carlos Mejia",
    "Email": "carlos.mejia@example.com",
    "Contraseña": "password123",
    "Telefono": 1234567890,
    "Ciudad": "Bogotá",
    "CodPostal": 110111,
    "Direccion": "Calle 45 No. 23",
    "FotoPerfil": ""
}

###

DELETE http://localhost:9000/api/usuarios/1 HTTP/1.1

###

PUT http://localhost:9000/api/usuarios/1 HTTP/1.1
Content-Type: application/json

{
    "Nombre": "Carlos Perez Actualizado",
    "Email": "carlos.perez.update@example.com",
    "Contraseña": "newpassword123",
    "Telefono": 9876543210,
    "Ciudad": "Barranquilla",
    "CodPostal": 220222,
    "Direccion": "Carrera 10 No. 25",
    "FotoPerfil": ""
}

###

POST http://localhost:9000/api/usuarios/upload/1 HTTP/1.1
Content-Type: multipart/form-data


